"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Shift={id:string;operator_name:string;cash_register_name?:string|null;status:string;opening_cash_cents:number;opened_at:string;closed_at?:string|null;expected_cash_cents?:number|null;declared_cash_cents?:number|null;difference_cents?:number|null;gross_sales_cents?:number|null;pix_cents?:number|null;card_cents?:number|null;cash_sales_cents?:number|null;sales_count?:number|null;closing_notes?:string|null};
type Product={id:string;name:string;barcode?:string|null;price_cents:number};
const money=(cents:number)=>(cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
export function CashierAdmin({initialShifts,initialProducts}:{initialShifts:Shift[];initialProducts:Product[]}){const supabase=useMemo(()=>createClient(),[]);const [products,setProducts]=useState(initialProducts);const [message,setMessage]=useState("");async function saveBarcode(product:Product,value:string){const barcode=value.trim()||null;const {error}=await supabase.from("products").update({barcode}).eq("id",product.id);if(error)setMessage(error.code==="23505"?"Esse código já está ligado a outro produto.":error.message);else{setProducts(current=>current.map(item=>item.id===product.id?{...item,barcode}:item));setMessage(`Código de ${product.name} salvo.`);}}
return <div className="cashier-admin-stack"><article className="panel cashier-launch"><div><small>OPERAÇÃO DO FUNCIONÁRIO</small><h2>Tela exclusiva do caixa.</h2><p>O funcionário entra com nome e senha, abre o turno e todas as vendas ficam registradas na responsabilidade dele.</p></div><Link className="button dark" href="/caixa/login" target="_blank">Abrir sistema do caixa ↗</Link></article>
<article className="panel"><div className="section-heading"><div><small>PRESTAÇÃO DE CONTAS</small><h2>Fechamentos de caixa.</h2><p>Conferência por operador, turno, forma de pagamento e diferença encontrada.</p></div></div><div className="team-report-scroll"><table className="table"><thead><tr><th>OPERADOR</th><th>ABERTURA</th><th>FECHAMENTO</th><th>VENDAS</th><th>DINHEIRO</th><th>PIX</th><th>CARTÕES</th><th>ESPERADO</th><th>DECLARADO</th><th>DIFERENÇA</th></tr></thead><tbody>{initialShifts.map(shift=><tr key={shift.id}><td><b>{shift.operator_name}</b><small>{shift.cash_register_name||"Caixa"} · {shift.sales_count||0} operações · {shift.status==="open"?"Aberto":"Fechado"}</small></td><td>{new Date(shift.opened_at).toLocaleString("pt-BR")}</td><td>{shift.closed_at?new Date(shift.closed_at).toLocaleString("pt-BR"):"Em andamento"}</td><td>{money(shift.gross_sales_cents||0)}</td><td>{money(shift.cash_sales_cents||0)}</td><td>{money(shift.pix_cents||0)}</td><td>{money(shift.card_cents||0)}</td><td>{shift.expected_cash_cents==null?"—":money(shift.expected_cash_cents)}</td><td>{shift.declared_cash_cents==null?"—":money(shift.declared_cash_cents)}</td><td className={(shift.difference_cents||0)===0?"money-in":"money-out"}>{shift.difference_cents==null?"—":money(shift.difference_cents)}</td></tr>)}</tbody></table></div>{!initialShifts.length&&<div className="empty-state">Nenhum expediente de caixa registrado.</div>}</article>
<article className="panel"><div className="section-heading"><div><small>LEITOR DE CÓDIGO DE BARRAS</small><h2>Códigos dos produtos.</h2><p>Cadastre uma vez. No caixa, o funcionário pode usar leitor USB/Bluetooth, câmera do celular ou digitar o código.</p></div></div>{message&&<div className="form-message">{message}</div>}<div className="barcode-admin-list">{products.map(product=><div key={product.id}><span><b>{product.name}</b><small>{money(product.price_cents)}</small></span><input key={product.barcode||"empty"} defaultValue={product.barcode||""} inputMode="numeric" placeholder="EAN, UPC ou código interno" onKeyDown={event=>{if(event.key==="Enter")void saveBarcode(product,event.currentTarget.value);}}/><button className="button outline" onClick={event=>{const input=event.currentTarget.previousElementSibling as HTMLInputElement;void saveBarcode(product,input.value);}}>Salvar</button></div>)}</div></article></div>}
