"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Register={id:string;name:string;active:boolean};
type Device={id:string;name:string;printer_name:string;sector:string;connection_type:string;paper_width:number;network_address?:string|null;auto_print:boolean;is_default:boolean;cash_register_id?:string|null;active:boolean;online:boolean;last_seen_at?:string|null};
const sectors:Record<string,string>={kitchen:"Cozinha",counter:"Balcão",cashier:"Caixa",bar:"Bar / bebidas",delivery:"Delivery",other:"Outro setor"};

export function MultiPrinterManager({establishmentId,establishmentName,initialDevices,initialRegisters}:{establishmentId:string;establishmentName:string;initialDevices:Device[];initialRegisters:Register[]}){
  const supabase=useMemo(()=>createClient(),[]);const [devices,setDevices]=useState(initialDevices);const [registers,setRegisters]=useState(initialRegisters);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  async function refresh(){const {data}=await supabase.rpc("list_printer_devices",{requested_establishment_id:establishmentId});if(Array.isArray(data))setDevices(data as Device[]);}
  useEffect(()=>{const timer=window.setInterval(()=>void refresh(),5000);return()=>window.clearInterval(timer);},[]);
  function downloadInstaller(token:string,name:string){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;if(!url||!key)return setMessage("Configuração pública indisponível.");const base=window.location.origin;const command=`@echo off\r\ntitle Instalador Mesa Viva\r\nset "MV_INSTALLER=%TEMP%\\MesaVivaInstaller.ps1"\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest -UseBasicParsing -Uri '${base}/mesa-viva-installer.ps1' -OutFile '%MV_INSTALLER%'"\r\nif errorlevel 1 goto erro\r\npowershell.exe -NoProfile -ExecutionPolicy Bypass -File "%MV_INSTALLER%" -SupabaseUrl "${url}" -AnonKey "${key}" -DeviceToken "${token}" -SiteBaseUrl "${base}"\r\nif errorlevel 1 goto erro\r\ndel "%MV_INSTALLER%" >nul 2>&1\r\necho Concluido. Esta impressora esta ativa no Mesa Viva.\r\npause\r\ndel "%~f0"\r\nexit /b 0\r\n:erro\r\necho Nao foi possivel concluir.\r\npause\r\nexit /b 1\r\n`;const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([command],{type:"application/octet-stream"}));a.download=`Ativar-${name.replace(/[^a-z0-9]+/gi,"-")}.cmd`;a.click();URL.revokeObjectURL(a.href);}
  async function addPrinter(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget,data=new FormData(form);const {data:created,error}=await supabase.rpc("register_printer_device",{requested_establishment_id:establishmentId,requested_name:String(data.get("name")),requested_sector:String(data.get("sector")),requested_connection_type:String(data.get("connection")),requested_paper_width:Number(data.get("paper")),requested_network_address:String(data.get("network")||""),requested_auto_print:data.get("auto")==="on",requested_is_default:data.get("default")==="on",requested_cash_register_id:String(data.get("register")||"")||null});setBusy(false);if(error)return setMessage(error.message);form.reset();downloadInstaller(String(created.token),String(created.name));setMessage("Cadastro criado. Abra o instalador baixado e escolha a impressora correta deste setor.");await refresh();}
  async function addRegister(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget,name=String(new FormData(form).get("name"));const {data,error}=await supabase.rpc("create_cash_register",{requested_establishment_id:establishmentId,requested_name:name});setBusy(false);if(error)return setMessage(error.message);setRegisters(v=>[...v,data as Register]);form.reset();setMessage(`${name} cadastrado e disponível para os operadores.`);}
  async function test(device:Device){setMessage(`Enviando teste para ${device.name}...`);const text=`${establishmentName}\n\nTESTE DE IMPRESSORA\n------------------------------\nDISPOSITIVO: ${device.name}\nSETOR: ${sectors[device.sector]}\nPAPEL: ${device.paper_width} mm\nDATA: ${new Date().toLocaleString("pt-BR")}\n------------------------------\nMESA VIVA`;const {error}=await supabase.rpc("queue_printer_test_device",{requested_device_id:device.id,requested_text:text});setMessage(error?error.message:"Teste enviado para a impressora selecionada.");}
  async function deactivate(device:Device){if(!window.confirm(`Desativar ${device.name}?`))return;const {error}=await supabase.rpc("deactivate_printer_device",{requested_device_id:device.id});setMessage(error?error.message:"Impressora desativada.");await refresh();}
  return <section className="panel multi-printer-manager"><div className="section-heading"><div><small>IMPRESSORAS E TERMINAIS</small><h2>Vários caixas e impressoras.</h2><p>Cadastre cada equipamento uma única vez. O sistema envia cozinha, balcão e vendas para a impressora correta.</p></div><span className="status-pill">{devices.filter(d=>d.online&&d.active).length} online</span></div>
    {message&&<div className="form-message">{message}</div>}
    <div className="printer-manager-grid"><form className="printer-manager-form" onSubmit={addPrinter}><h3>Nova impressora</h3><div className="form-grid"><div className="field"><label>NOME</label><input name="name" required placeholder="Ex.: Impressora Caixa 2"/></div><div className="field"><label>SETOR</label><select name="sector"><option value="kitchen">Cozinha</option><option value="counter">Balcão</option><option value="cashier">Caixa</option><option value="bar">Bar / bebidas</option><option value="delivery">Delivery</option><option value="other">Outro</option></select></div><div className="field"><label>CONEXÃO</label><select name="connection"><option value="usb">USB</option><option value="bluetooth">Bluetooth</option><option value="network">Wi-Fi / rede</option></select></div><div className="field"><label>PAPEL</label><select name="paper"><option value="58">58 mm</option><option value="80">80 mm</option></select></div><div className="field"><label>CAIXA VINCULADO (OPCIONAL)</label><select name="register"><option value="">Nenhum</option>{registers.filter(r=>r.active).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></div><div className="field"><label>IP / NOME NA REDE (OPCIONAL)</label><input name="network" placeholder="192.168.0.50"/></div></div><label className="check-line"><input type="checkbox" name="auto"/><span>Impressão automática neste setor</span></label><label className="check-line"><input type="checkbox" name="default"/><span>Impressora principal deste setor</span></label><button className="button dark" disabled={busy}>Cadastrar e ativar impressora</button></form>
      <form className="printer-manager-form" onSubmit={addRegister}><h3>Terminais de caixa</h3><p>Crie Caixa 1, Caixa 2 e quantos pontos de venda forem necessários.</p><div className="field"><label>NOME DO TERMINAL</label><input name="name" required placeholder="Ex.: Caixa 2"/></div><button className="button outline" disabled={busy}>Adicionar caixa</button><div className="register-chip-list">{registers.map(r=><span key={r.id}>{r.name}<small>{r.active?"Ativo":"Inativo"}</small></span>)}</div></form></div>
    <div className="printer-device-list">{devices.map(device=><article key={device.id} className={!device.active?"disabled":""}><div><span className={`connector-status-dot ${device.online?"online":""}`}/><small>{sectors[device.sector]||device.sector}</small><h3>{device.name}</h3><p>{device.printer_name} · {device.connection_type.toUpperCase()} · {device.paper_width} mm</p><p>{device.cash_register_id?`Vinculada a ${registers.find(r=>r.id===device.cash_register_id)?.name||"caixa"}`:"Sem caixa exclusivo"} {device.is_default?"· Principal":""}</p></div><div className="printer-device-actions"><b>{device.online?"Online":"Aguardando conexão"}</b>{device.active&&<button className="button outline" disabled={!device.online} onClick={()=>void test(device)}>Imprimir teste</button>}{device.active&&<button className="text-danger" onClick={()=>void deactivate(device)}>Desativar</button>}</div></article>)}</div>{!devices.length&&<div className="empty-state">Nenhuma impressora cadastrada. Use o formulário acima para começar.</div>}
  </section>;
}
