"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Product={id:string;name:string;price_cents:number;barcode?:string|null;category_id?:string|null};
type CartItem={key:string;product_id?:string;name:string;unit_price_cents:number;quantity:number;barcode?:string|null};
type Order={id:string;order_number:number;customer_name:string;total_cents:number;payment_method?:string|null;created_at:string;order_items:{product_name:string;quantity:number;total_cents:number}[]};
type Payment={id:string;waiter_name?:string|null;payment_method:string;amount_cents:number;table_number?:string|null;confirmed_at:string};
type Shift={id:string;operator_name:string;status:"open"|"closed";opening_cash_cents:number;opened_at:string;expected_cash_cents?:number|null;declared_cash_cents?:number|null;difference_cents?:number|null;gross_sales_cents?:number|null;pix_cents?:number|null;card_cents?:number|null;cash_sales_cents?:number|null;sales_count?:number|null;closed_at?:string|null};
type Sale={id:string;sale_number:number;operator_name:string;payment_method:string;total_cents:number;created_at:string;source:string};
type Movement={id:string;movement_type:"inflow"|"outflow";category:string;payment_method:string;amount_cents:number;description?:string|null;occurred_at:string;pos_sale_id?:string|null};

const money=(cents:number)=>(cents/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const cents=(value:string)=>Math.round(Number(value.replace(/\./g,"").replace(",","."))*100);
const paymentLabel:Record<string,string>={cash:"Dinheiro",pix:"Pix",credit_card:"Crédito",debit_card:"Débito",transfer:"Transferência",other:"Outro",mixed:"Misto"};

export function PosConsole({establishmentName,employeeName,initialShift,products,initialOrders,tablePayments,initialSales,initialMovements}:{establishmentName:string;employeeName:string;initialShift:Shift|null;products:Product[];initialOrders:Order[];tablePayments:Payment[];initialSales:Sale[];initialMovements:Movement[]}){
  const supabase=useMemo(()=>createClient(),[]);const [shift,setShift]=useState(initialShift);const [orders,setOrders]=useState(initialOrders);const [sales,setSales]=useState(initialSales);const [movements,setMovements]=useState(initialMovements);const [cart,setCart]=useState<CartItem[]>([]);const [selectedOrder,setSelectedOrder]=useState<Order|null>(null);const [search,setSearch]=useState("");const [payment,setPayment]=useState("cash");const [cashReceived,setCashReceived]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [scanner,setScanner]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);
  const filtered=products.filter(product=>search.length>1&&(product.name.toLowerCase().includes(search.toLowerCase())||product.barcode===search.trim())).slice(0,12);
  const total=selectedOrder?.total_cents||cart.reduce((sum,item)=>sum+item.unit_price_cents*item.quantity,0);const change=payment==="cash"&&cashReceived?Math.max(cents(cashReceived)-total,0):0;
  const shiftPayments=tablePayments.filter(item=>shift&&new Date(item.confirmed_at)>=new Date(shift.opened_at));
  const gross=sales.reduce((sum,item)=>sum+item.total_cents,0)+shiftPayments.reduce((sum,item)=>sum+item.amount_cents,0);

  function add(product:Product){setCart(current=>{const found=current.find(item=>item.product_id===product.id);return found?current.map(item=>item.key===found.key?{...item,quantity:item.quantity+1}:item):[...current,{key:product.id,product_id:product.id,name:product.name,unit_price_cents:product.price_cents,quantity:1,barcode:product.barcode}]});setSearch("");setSelectedOrder(null);}
  function addByCode(code:string){const product=products.find(item=>item.barcode===code.trim());if(product){add(product);setMessage(`${product.name} adicionado.`);}else setMessage("Código não encontrado. Digite o item manualmente.");}

  useEffect(()=>{if(!scanner)return;let stream:MediaStream|null=null;let timer:number|undefined;let stopped=false;(async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play();}const Detector=(globalThis as unknown as {BarcodeDetector?:new(args:{formats:string[]})=>{detect(source:HTMLVideoElement):Promise<{rawValue:string}[]>}}).BarcodeDetector;if(!Detector){setMessage("Este celular não possui leitura automática. Use o campo de código.");return;}const detector=new Detector({formats:["ean_13","ean_8","code_128","upc_a","upc_e"]});timer=window.setInterval(async()=>{if(stopped||!videoRef.current)return;const found=await detector.detect(videoRef.current);if(found[0]?.rawValue){addByCode(found[0].rawValue);setScanner(false);}},450);}catch{setMessage("Não foi possível abrir a câmera. Permita o acesso ou digite o código.");setScanner(false);}})();return()=>{stopped=true;if(timer)window.clearInterval(timer);stream?.getTracks().forEach(track=>track.stop());};},[scanner]);

  async function open(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=new FormData(event.currentTarget);const value=cents(String(form.get("opening")));const {data,error}=await supabase.rpc("open_cash_shift",{requested_opening_cash_cents:value});if(error)setMessage(error.message);else setShift(data as Shift);setBusy(false);}
  async function checkout(){if(!shift||(!selectedOrder&&!cart.length))return;setBusy(true);setMessage("");const received=payment==="cash"?cents(cashReceived||String(total/100)):null;const {data,error}=await supabase.rpc("register_pos_sale",{requested_shift_id:shift.id,requested_items:cart.map(item=>({product_id:item.product_id,name:item.name,unit_price_cents:item.unit_price_cents,quantity:item.quantity,barcode:item.barcode})),requested_payment_method:payment,requested_customer_name:null,requested_source_order_id:selectedOrder?.id||null,requested_cash_received_cents:received});if(error)setMessage(error.message);else{setSales(current=>[{...(data as Sale),created_at:new Date().toISOString()},...current]);if(selectedOrder)setOrders(current=>current.filter(item=>item.id!==selectedOrder.id));setCart([]);setSelectedOrder(null);setCashReceived("");setMessage(`Venda #${data.sale_number} concluída por ${employeeName}. Troco: ${money(data.change_cents||0)}.`);}setBusy(false);}
  async function adjustment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!shift)return;setBusy(true);const formElement=event.currentTarget;const form=new FormData(formElement);const {data,error}=await supabase.rpc("record_cash_adjustment",{requested_shift_id:shift.id,requested_movement_type:String(form.get("type")),requested_category:String(form.get("category")),requested_payment_method:String(form.get("method")),requested_amount_cents:cents(String(form.get("amount"))),requested_description:String(form.get("description")||"")});if(error)setMessage(error.message);else{setMovements(current=>[data as Movement,...current]);setMessage("Movimentação registrada no seu nome.");formElement.reset();}setBusy(false);}
  async function close(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!shift)return;setBusy(true);const form=new FormData(event.currentTarget);const {data,error}=await supabase.rpc("close_cash_shift",{requested_shift_id:shift.id,requested_declared_cash_cents:cents(String(form.get("declared"))),requested_notes:String(form.get("notes")||"")});if(error)setMessage(error.message);else{setShift(data as Shift);setMessage("Caixa fechado e relatório gerado.");}setBusy(false);}
  async function logout(){await supabase.auth.signOut();window.location.replace("/caixa/login");}

  if(!shift)return <main className="pos-shell"><header className="pos-top"><div><small>{establishmentName}</small><h1>Abrir caixa.</h1><p>Operador responsável: <b>{employeeName}</b></p></div><button className="button outline" onClick={logout}>Sair</button></header><section className="pos-opening panel"><h2>Informe o fundo de caixa</h2><p>Conte o dinheiro inicial da gaveta. Esse valor será usado na conferência final.</p><form className="form" onSubmit={open}><div className="field"><label>VALOR INICIAL EM DINHEIRO</label><input name="opening" inputMode="decimal" required placeholder="0,00" /></div><button className="button dark wide" disabled={busy}>Abrir meu caixa →</button></form>{message&&<div className="form-message">{message}</div>}</section></main>;
  if(shift.status==="closed")return <main className="pos-shell"><header className="pos-top"><div><small>FECHAMENTO CONCLUÍDO</small><h1>Prestação de contas.</h1><p>{shift.operator_name} · {new Date(shift.closed_at||Date.now()).toLocaleString("pt-BR")}</p></div><button className="button outline" onClick={logout}>Sair</button></header><section className="pos-close-report"><article><small>VENDAS</small><strong>{money(shift.gross_sales_cents||0)}</strong><span>{shift.sales_count||0} operações</span></article><article><small>DINHEIRO ESPERADO</small><strong>{money(shift.expected_cash_cents||0)}</strong><span>Inclui fundo inicial</span></article><article><small>DINHEIRO DECLARADO</small><strong>{money(shift.declared_cash_cents||0)}</strong><span>Contagem do operador</span></article><article className={(shift.difference_cents||0)===0?"balanced":"divergent"}><small>DIFERENÇA</small><strong>{money(shift.difference_cents||0)}</strong><span>{(shift.difference_cents||0)===0?"Caixa conferido":"Requer conferência"}</span></article></section><button className="button dark" onClick={()=>window.location.reload()}>Iniciar novo expediente</button></main>;

  return <main className="pos-shell"><header className="pos-top"><div><small>{establishmentName} · CAIXA ABERTO</small><h1>Olá, {employeeName}.</h1><p>Aberto às {new Date(shift.opened_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})} · movimento atual {money(gross)}</p></div><div className="pos-top-actions"><button className="button outline" onClick={logout}>Sair</button></div></header>
    {message&&<div className="form-message pos-message">{message}</div>}
    <div className="pos-layout"><section className="pos-products panel"><div className="section-heading"><div><small>VENDA RÁPIDA</small><h2>Produtos e código.</h2></div><button className="button outline" onClick={()=>setScanner(value=>!value)}>{scanner?"Fechar câmera":"Ler código pela câmera"}</button></div>{scanner&&<div className="barcode-camera"><video ref={videoRef} playsInline muted/><span>Aponte para o código de barras</span></div>}<div className="pos-search"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();addByCode(search);}}} placeholder="Buscar produto ou digitar/ler código" autoFocus/><button onClick={()=>addByCode(search)}>Adicionar código</button></div>{search&&<div className="pos-product-grid">{filtered.map(product=><button key={product.id} onClick={()=>add(product)}><b>{product.name}</b><span>{money(product.price_cents)}</span><small>{product.barcode||"Sem código"}</small></button>)}</div>}<ManualItem onAdd={item=>{setCart(current=>[...current,item]);setSelectedOrder(null);}}/>
      <div className="pos-pending"><h3>Pedidos do cardápio aguardando caixa</h3>{orders.length?orders.map(order=><button key={order.id} className={selectedOrder?.id===order.id?"selected":""} onClick={()=>{setSelectedOrder(order);setCart([]);}}><span><b>Pedido #{order.order_number}</b><small>{order.customer_name} · {order.order_items.map(item=>`${item.quantity}x ${item.product_name}`).join(", ")}</small></span><strong>{money(order.total_cents)}</strong></button>):<div className="empty-state">Nenhum pedido aguardando recebimento.</div>}</div>
    </section><aside className="pos-cart panel"><small>VENDA ATUAL</small><h2>{selectedOrder?`Pedido #${selectedOrder.order_number}`:"Cupom do caixa"}</h2>{selectedOrder?<div className="pos-cart-items">{selectedOrder.order_items.map((item,index)=><div key={index}><span>{item.quantity}x {item.product_name}</span><b>{money(item.total_cents)}</b></div>)}</div>:<div className="pos-cart-items">{cart.map(item=><div key={item.key}><span><button onClick={()=>setCart(current=>current.filter(row=>row.key!==item.key))}>×</button>{item.quantity}x {item.name}</span><span className="qty"><button onClick={()=>setCart(current=>current.map(row=>row.key===item.key?{...row,quantity:Math.max(1,row.quantity-1)}:row))}>−</button><button onClick={()=>setCart(current=>current.map(row=>row.key===item.key?{...row,quantity:row.quantity+1}:row))}>+</button><b>{money(item.unit_price_cents*item.quantity)}</b></span></div>)}{!cart.length&&<div className="empty-state">Leia um código, procure um produto ou adicione item avulso.</div>}</div>}<div className="pos-total"><span>TOTAL</span><strong>{money(total)}</strong></div><div className="field"><label>FORMA DE PAGAMENTO</label><select value={payment} onChange={e=>setPayment(e.target.value)}><option value="cash">Dinheiro</option><option value="pix">Pix</option><option value="credit_card">Cartão de crédito</option><option value="debit_card">Cartão de débito</option><option value="transfer">Transferência</option><option value="other">Outro</option></select></div>{payment==="cash"&&<div className="field"><label>VALOR RECEBIDO</label><input value={cashReceived} onChange={e=>setCashReceived(e.target.value)} inputMode="decimal" placeholder={money(total)}/><small>Troco: <b>{money(change)}</b></small></div>}<button className="button dark wide" disabled={busy||total<=0} onClick={checkout}>{busy?"Processando...":"Finalizar e registrar venda"}</button></aside></div>
    <section className="pos-bottom-grid"><article className="panel"><h2>Reforço, sangria ou despesa</h2><form className="form" onSubmit={adjustment}><div className="form-grid"><div className="field"><label>OPERAÇÃO</label><select name="type"><option value="outflow">Saída</option><option value="inflow">Entrada</option></select></div><div className="field"><label>CATEGORIA</label><select name="category"><option>Sangria</option><option>Despesa</option><option>Reforço de caixa</option><option>Outro</option></select></div><div className="field"><label>FORMA</label><select name="method"><option value="cash">Dinheiro</option><option value="pix">Pix</option><option value="transfer">Transferência</option><option value="other">Outro</option></select></div><div className="field"><label>VALOR</label><input name="amount" required inputMode="decimal" placeholder="0,00"/></div><div className="field full"><label>MOTIVO / COMPROVAÇÃO</label><input name="description" required/></div></div><button className="button outline">Registrar movimentação</button></form></article><article className="panel"><h2>Fechar o caixa</h2><p>Conte o dinheiro físico. O sistema compara com vendas, mesas, reforços e saídas.</p><form className="form" onSubmit={close}><div className="field"><label>DINHEIRO CONTADO NA GAVETA</label><input name="declared" required inputMode="decimal" placeholder="0,00"/></div><div className="field"><label>OBSERVAÇÃO DO FECHAMENTO</label><input name="notes" placeholder="Explique qualquer diferença"/></div><button className="button dark wide" disabled={busy}>Fechar e gerar relatório</button></form></article></section>
    <section className="panel"><div className="section-heading"><div><small>CONTAS FECHADAS PELOS GARÇONS</small><h2>Recebimentos do salão.</h2><p>Entram automaticamente no fechamento do caixa, com o nome do responsável.</p></div></div><div className="team-report-scroll"><table className="table"><thead><tr><th>HORÁRIO</th><th>GARÇOM</th><th>MESA</th><th>FORMA</th><th>VALOR</th></tr></thead><tbody>{shiftPayments.map(item=><tr key={item.id}><td>{new Date(item.confirmed_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}</td><td>{item.waiter_name||"Equipe"}</td><td>{item.table_number||"—"}</td><td>{paymentLabel[item.payment_method]||item.payment_method}</td><td><b>{money(item.amount_cents)}</b></td></tr>)}</tbody></table></div></section>
  </main>;
}

function ManualItem({onAdd}:{onAdd:(item:CartItem)=>void}){const [open,setOpen]=useState(false);function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const value=cents(String(form.get("price")));if(value<0)return;onAdd({key:crypto.randomUUID(),name:String(form.get("name")),unit_price_cents:value,quantity:1,barcode:String(form.get("barcode")||"")||null});setOpen(false);}return <div className="manual-item"><button className="button outline" onClick={()=>setOpen(value=>!value)}>+ Item fora do cardápio</button>{open&&<form className="form form-grid" onSubmit={save}><div className="field"><label>DESCRIÇÃO</label><input name="name" required placeholder="Ex.: Refrigerante avulso"/></div><div className="field"><label>VALOR</label><input name="price" required inputMode="decimal" placeholder="0,00"/></div><div className="field"><label>CÓDIGO (OPCIONAL)</label><input name="barcode" inputMode="numeric"/></div><button className="button dark">Adicionar</button></form>}</div>}
